# Generated by Django 3.2.7 on 2021-09-06 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="next_lesson",
            field=models.DateTimeField(null=True),
        ),
    ]
